# Generated by Django 4.1.4 on 2023-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_category_remove_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
