# Generated by Django 4.1.5 on 2023-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('<QuerySet [<Category: Nombre: Pantalones>, <Category: Nombre: Remeras>, <Category: Nombre: Vestidos>]>', '<QuerySet [<Category: Nombre: Pantalones>, <Category: Nombre: Remeras>, <Category: Nombre: Vestidos>]>')], default='', max_length=150),
        ),
    ]
