# Generated by Django 4.1.5 on 2023-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
